### PR TITLE
fix: use SCP protocol for single-file transfers

### LINKED ISSUE #290: Slow SCP file copy from host to guest
# Problem

Copying a single large file from the host to the guest VM is slow. For example, it took approximately two minutes to copy a 280 MB file.

```console
me@host:~\
$ time cubic scp large.tar.gz guest:/home/cubic/

real	2m12.520s
user	0m3.656s
sys	0m1.350s

me@host:~\
$ ls -lh large.tar.gz
-rw-rw-r-- 1 me me 274M Mar  2 15:50 large.tar.gz
```

Copying smaller files, however, is fast.

### PR DESCRIPTION
**Pull request by TickTockBent**
## Problem

`cubic scp large.tar.gz guest:/home/cubic/` takes over two minutes for a 274 MB file (#290). That's roughly 2 MB/s on loopback, which is wild.

I dug into the `russh-sftp` internals and found the bottleneck: its `AsyncWrite` implementation awaits a server ACK for every single write request. No pipelining at all. Each `poll_write()` call blocks on a full SFTP request-response round-trip before it'll accept more data. Doesn't matter how fast the link is.

The upstream issue is [russh-sftp#70](https://github.com/AspectUnk/russh-sftp/issues/70), open since June 2025 with no fix.

## Fix

Rather than waiting on upstream, this adds an SCP-based transfer path for single-file copies. SCP streams raw bytes through an SSH exec channel (`scp -t` / `scp -f`) with no per-packet ACKs, so you get full SSH channel throughput.

| Direction | Detection | Method |
|-----------|-----------|--------|
| Host to Guest (file) | `local_path.is_file()` | SCP upload via `scp -t` |
| Guest to Host | Try SCP first | SCP download via `scp -f`, SFTP fallback |
| Directories | n/a | SFTP (unchanged) |
| Guest to Guest | n/a | SFTP (unchanged) |

Directory copies and guest-to-guest transfers still go through SFTP. For the guest-to-host case, we try SCP first and fall back to SFTP if it fails (e.g., the source is a directory).

## Changes

- **`src/ssh_cmd/scp.rs`** (new): SCP upload and download over a raw `russh` exec channel. 64KB streaming buffer, progress reporting via the existing `TransferView`.
- **`src/ssh_cmd/russh.rs`**: `async_copy` now detects the transfer direction and routes single files through SCP.
- **`src/error.rs`**: Added `Scp(String)` error variant.
- **`src/ssh_cmd.rs`**: Registered the new `scp` module.

## Checks

- `cargo fmt --check` clean
- `cargo clippy -- -D warnings` clean
- `cargo test` 104/104

## Test plan

- [ ] `cubic scp large_file.tar.gz guest:/home/cubic/` (verify speed improvement)
- [ ] `cubic scp guest:/home/cubic/large_file.tar.gz .` (verify download)
- [ ] `cubic scp local_dir/ guest:/home/cubic/` (verify directory falls back to SFTP)
- [ ] Progress bar renders correctly during transfer

Closes #290

// squashing bugs, one cherry-pick at a time

### CODE REVIEW

File: src/ssh_cmd/scp.rs [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+
+    let mut header_bytes = Vec::new();
+    loop {
+        let mut c = [0u8; 1];
+        stream.read_exact(&mut c).await?;
+        if c[0] == b'\n' {
+            break;
+        }
+        header_bytes.push(c[0]);
+    }
```
Comment (rogkne) [inline src/ssh_cmd/scp.rs]: This loop just reads a single line. I think it would be cleaner to use `BufReader.read_line()`

see: https://docs.rs/tokio/latest/tokio/io/struct.BufReader.html
